name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Android:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup msbuild
              uses: microsoft/setup-msbuild@v1

            - name: Restore NuGet packages
              run: msbuild -t:restore
              working-directory: Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.Android

            - name: msbuild
              # TODO: Enable `-warnAsError` flag once package conflicts are resolved.
              run: msbuild
              working-directory: Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.Android
    iOS:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            # Fixes error when using newer NuGet packages that require a minimum version of Xcode
            - name: Use Xcode 14.0.1
              uses: maxim-lobanov/setup-xamarin@v1
              with:
                  xcode-version: 14.0.1

            # The following two workaround steps can be removed when the following github issue is resolved: https://github.com/actions/virtual-environments/issues/5768
            - name: Restore Workaround Remove
              run: rm -rf ~/.config/NuGet/NuGet.Config
              shell: bash

            - name: Restore Workaround List
              run: dotnet nuget list source
              shell: bash

            - name: Restore NuGet packages
              run: msbuild -t:restore
              working-directory: Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.iOS

            - name: msbuild
              # TODO: Enable `-warnAsError` flag once package conflicts are resolved.
              run: msbuild
              working-directory: Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.iOS
    Windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup msbuild
              uses: microsoft/setup-msbuild@v1
            
            - name: "Update windows SDK"
              uses: fbactions/setup-winsdk@v1
              with:
                winsdk-build-version: 18362

            - name: Restore NuGet packages
              run: msbuild -t:restore
              working-directory: Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.UWP

            - name: msbuild
              # TODO: Enable `-warnAsError` flag once XF is updated, and warnings aren't shown:
              # https://developercommunity.visualstudio.com/content/problem/1251681/xamarinforms-application-warning.html
              run: msbuild
              working-directory: Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.UWP
